media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  # ===== ARTICLES (now identical to TEAM structure) =====
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Category
        type: string
        required: true
      - name: image
        label: Featured Image
        type: image
        media: true
        required: true
      # ✅ ADD THIS: article body as a 'text' field (like 'bio' in team)
      - name: body
        label: Article Content
        type: text
        required: true
        description: "Write your article content here (use Markdown syntax if desired)"

  # ===== TEAM (unchanged, working) =====
  - name: team
    label: Team Members
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: role
        label: Role
        type: string
        required: true
      - name: bio
        label: Bio
        type: text
        required: true
      - name: photo
        label: Photo
        type: image
        media: true
        required: false
      - name: order
        label: Order
        type: number
        default: 999