media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        type: string
        required: true
      - name: slug
        type: string
        required: true
      - name: excerpt
        type: text
        required: true
      - name: date
        type: date
        required: true
      - name: category
        type: select
        options:
          - Environment
          - Education
          - Health
          - Community
        required: true
      - name: image
        type: image
        media: true
        required: true

  - name: team
    label: Team Members
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: name
        type: string
        required: true
      - name: slug
        type: string
        required: true
      - name: role
        type: string
        required: true
      - name: bio
        type: text
        required: true
      - name: photo
        type: image
        media: true
        required: false
      - name: order
        type: number
        default: 999