# .pages.yml
# Configuration for PagesCMS (https://pagescms.dev)

media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  # Collection: Articles (for Activities page)
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug (URL-friendly ID)
        type: string
        required: true
        description: "Used in URL: /article/your-slug"
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: date
        label: Publish Date
        type: date
        required: true
        format: "YYYY-MM-DD"
      - name: category
        label: Category
        type: select
        options:
          - Environment
          - Education
          - Health
          - Community
        required: true
      - name: image
        label: Featured Image
        type: image
        media: true
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true

  # Collection: Team Members
  - name: team
    label: Team Members
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: slug
        label: Slug (URL-friendly ID)
        type: string
        required: true
        description: "Used for sorting; not in URL (we use single /team page)"
      - name: role
        label: Role / Title
        type: string
        required: true
      - name: bio
        label: Short Bio
        type: text
        required: true
      - name: photo
        label: Photo
        type: image
        media: true
        required: false
      - name: order
        label: Display Order
        type: number
        default: 999
        description: "Lower numbers appear first"

# Optional: Hide Settings tab (since we don't need it)
settings:
  hide: false