# .pages.yml
# Place this file in the ROOT of your GitHub repository

media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  # ===== ARTICLES (for /activities and /article/:slug) =====
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug (URL ID)
        type: string
        required: true
        description: "Use lowercase letters and hyphens only (e.g., river-cleanup)"
      - name: excerpt
        label: Excerpt
        type: text
        required: true
        description: "Short summary shown in article listings"
      - name: date
        label: Publish Date
        type: date
        required: true
        format: "YYYY-MM-DD"
      - name: category
        label: Category
        type: select
        options:
          - Environment
          - Education
          - Health
          - Community
        required: true
      - name: image
        label: Featured Image
        type: image
        media: true
        required: true
        description: "Image shown in listings and article header"

  # ===== TEAM MEMBERS (for /team page) =====
  - name: team
    label: Team Members
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
        description: "Used for filename and sorting (e.g., ayesha-rahman)"
      - name: role
        label: Role / Title
        type: string
        required: true
      - name: bio
        label: Short Bio
        type: text
        required: true
      - name: photo
        label: Photo
        type: image
        media: true
        required: false
      - name: order
        label: Display Order
        type: number
        default: 999
        description: "Lower numbers appear first (e.g., 1, 2, 3)"

 